"use client"

import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Copy, Check, FileText } from "lucide-react"
import { useState } from "react"

interface ReportViewerProps {
    markdown: string;
}

export default function ReportViewer({ markdown }: ReportViewerProps) {
    const [copied, setCopied] = useState(false)

    const handleCopy = () => {
        navigator.clipboard.writeText(markdown)
        setCopied(true)
        setTimeout(() => setCopied(false), 2000)
    }

    if (!markdown) return null;

    return (
        <Card className="w-full shadow-lg border-neutral-200 dark:border-neutral-800 print:shadow-none print:border-none">
            <CardHeader className="flex flex-row items-center justify-between border-b pb-4">
                <div className="space-y-1">
                    <CardTitle className="flex items-center gap-2">
                        <FileText className="h-5 w-5 text-blue-600" />
                        Research Report
                    </CardTitle>
                    <CardDescription>Generated by AI Agent</CardDescription>
                </div>
                <Button variant="outline" size="sm" onClick={handleCopy} className="gap-2">
                    {copied ? <Check className="h-4 w-4 text-green-500" /> : <Copy className="h-4 w-4" />}
                    {copied ? "Copied" : "Copy Markdown"}
                </Button>
            </CardHeader>
            <CardContent className="pt-6">
                <div className="break-keep prose prose-neutral dark:prose-invert max-w-none 
          prose-headings:font-bold 
          prose-h1:text-3xl prose-h1:mb-6 prose-h1:pb-3 prose-h1:border-b-2 prose-h1:border-blue-500
          prose-h3:text-xl prose-h3:mt-8 prose-h3:mb-3 prose-h3:text-neutral-900 dark:prose-h3:text-neutral-100
          prose-p:leading-relaxed 
          prose-li:my-1 prose-li:leading-relaxed
          prose-a:text-blue-600 dark:prose-a:text-blue-400 prose-a:no-underline hover:prose-a:underline
          prose-img:rounded-lg prose-img:shadow-sm prose-img:max-w-sm prose-img:max-h-64 prose-img:object-cover prose-img:my-4
          prose-hr:my-8 prose-hr:border-neutral-200 dark:prose-hr:border-neutral-800
          prose-strong:text-neutral-900 dark:prose-strong:text-neutral-100 prose-strong:font-semibold
          prose-table:border-collapse prose-table:w-full prose-table:my-4
          prose-th:border prose-th:border-neutral-300 dark:prose-th:border-neutral-700 prose-th:bg-neutral-100 dark:prose-th:bg-neutral-800 prose-th:p-2
          prose-td:border prose-td:border-neutral-300 dark:prose-td:border-neutral-700 prose-td:p-2
          prose-code:text-sm prose-code:bg-neutral-100 dark:prose-code:bg-neutral-800 prose-code:px-1 prose-code:py-0.5 prose-code:rounded
          prose-pre:bg-neutral-100 dark:prose-pre:bg-neutral-900 prose-pre:p-4 prose-pre:rounded-lg prose-pre:overflow-x-auto">
                    <ReactMarkdown remarkPlugins={[remarkGfm]}>{markdown}</ReactMarkdown>
                </div>
            </CardContent>
        </Card>
    )
}
